# Über uns

[Department of Clinical Research](https://www.dcr.unibe.ch/):

The Department of Clinical Research (DCR) is your first point of contact when it comes to any aspect of clinical research, from concept to study conduct and on-site management. The DCR provides the central organization for expertise, innovation, leadership, contemporary pedagogy, and centralized facilities for supporting clinical researchers. DCR is the academic center for knowledge transfer and services related to clinical research. It offers clinical researchers full support from study design to study conduct. The Clinical Investigation Unit (CIU), Clinical Trials Unit (CTU Bern) and the Medical Data Science Unit work together under the DCR umbrella to provide comprehensive support for patient-centered research.

[CTU Bern](https://www.ctu.unibe.ch/):

CTU Bern is the clinical trials unit of the Faculty of Medicine of the University of Bern and the DCR and provides comprehensive support for patient-centered research in the areas of data management, clinical study management, statistics & methodology, monitoring and quality management.

[CIU Bern](https://www.ciu.unibe.ch/):

The Clinical Investigation Unit is the unit within DCR that has operational expertise for all aspects of clinical research from start up to completion and dissemination of results. We have strong patient engagement and are assisting in any way to ensure trial conduct is optimal. We are happy to engage in any stage of trial even if the trial has commenced. We operate on a flexible modular fashion to best enhance each individual collaboration.