project:
  type: website
  output-dir: docs
  
website:
  title: "Die reaction-Studie"
  search: false
  favicon: /Logos/Reaction_Logo.png
  margin-header: |
    ![](/Logos/Reaction_Logo.png){width="25%"}
    [![Link](/Logos/01_DCR_CMYK_POS.jpg){width="75%"}](https://www.dcr.unibe.ch/)
  navbar:

    title: false
    logo: /Logos/Reaction_Logo.png
    left:
      - index.qmd
      - 01_background.qmd
      - 02_results.qmd
      - 03_about.qmd
format:
  html:
    toc: true
    font-family: Arial
    toc-location: left
    toc-depth: 4
    toc-title: "Inhalt auf dieser Seite"
    grid:
      sidebar-width: 300px
      body-width: 800px
      margin-width: 450px
    theme: cosmo
    linestretch: 1.5
    fontsize: 1.5em




