project:
  type: website
  output-dir: docs
  
website:
  title: "![](logos/Reaction_Logo.png)"
  margin-header: | 
    ![](/Logos/01_DCR_CMYK_POS.jpg){width="75%"}
    ![](/Logos/logo_unibern_squid3.png){width="50%"}
  navbar:
    left:
      - index.qmd
      - xyz.qmd
      - results.qmd
format:
  html:
    toc: true
    toc-location: left
    toc-depth: 4
    toc-title: "Inhalt auf dieser Seite"
    grid:
      sidebar-width: 300px
      body-width: 800px
      margin-width: 450px
    theme: cosmo
    linestretch: 2




