project:
  type: website
  output-dir: docs
  
website:
  title: "Die reaction-Studie"
  search: false
  favicon: /Logos/Reaction_Logo.png
  body-header: |
    ![](/Logos/reaction-Sticker_20x15cm.png){width="40%"}
  navbar:
    title: false
    logo: /Logos/Reaction_Logo.png
    left:
      - index.qmd
      - 01_background.qmd
      - 02_results.qmd

format:
  html:
    toc: true
    mainfont: Arial
    toc-location: left
    toc-depth: 4
    toc-title: " "
    grid:
      sidebar-width: 300px
      body-width: 800px
      margin-width: 450px
    theme: cosmo
    linestretch: 1.5
    fontsize: 1.5em




