project:
  type: website
  output-dir: docs
  
website:
  title: "![](/Logos/Reaction_Logo.png)"
  margin-header: |
    [![Link](/Logos/logo_unibern_squid3.png){width="50%"}](https://www.unibe.ch/)
    [![Link](/Logos/01_DCR_CMYK_POS.jpg){width="75%"}](https://www.dcr.unibe.ch/)
  navbar:
    left:
      - index.qmd
      - 01_background.qmd
      - 02_results.qmd
format:
  html:
    toc: true
    toc-location: left
    toc-depth: 4
    toc-title: "Inhalt auf dieser Seite"
    grid:
      sidebar-width: 300px
      body-width: 800px
      margin-width: 450px
    theme: cosmo
    linestretch: 2




