# Die reaction-Studie

**Demonstration: reaction-Studie im sitem-insel am «Tag der offenen Tür», 2. Dezember 2023**

Am «Tag der Offenen Tür» führt das [Departement für klinische Forschung (DCR)](https://www.dcr.unibe.ch/) mit seinen Units [CTU Bern](https://www.ctu.unibe.ch/) und [CIU Bern](https://www.ciu.unibe.ch/) die reaction-Studie durch. Sie dient als Demonstration zur Veranschaulichung einer randomisierten kontrollierten Studie und gibt Einblick in alle Stationen eines Studienablaufs: von der Studieninformation und Einwilligung, der Anamnese und Randomisierung, über die Intervention bis hin zur Datenerfassung und Auswertung.

Untersucht wird die Wirkung des reaction-Drinks auf die Reaktionsfähigkeit und das mentale Fitnessempfinden bei Besucher:innen am «Tag der offenen Tür». Sei live dabei und erfahre, was du gerne wissen möchtest!

Melde dich zur Studienteilnahme und finde heraus, ob der reaction-Drink dir Power verleiht – frei nach dem Motto «nicht besser, aber schneller»!

Samstag, 2. Dezember 2023, «Tag der offenen Tür» sitem-insel
Department of Clinical Research, 1. OG Ost
Studienteilnahme: 10.00 − 14.00 Uhr
Auswertung laufend bis 16.00 Uhr

**Hinweis:**

Des Weiteren machen wir gerne darauf aufmerksam, dass von 13.00-14.30 Uhr ein offenes Patient:innen-Forum unter der Leitung von Dr. med. Sven Trelle, Direktor CTU Bern, und Carmen Jörg Fetscherin, Head CIU, stattfinden wird.

Das Department of Clinical Research (DCR) ist das akademische Zentrum für Wissenstransfer und Dienstleistungen im Zusammenhang mit klinischer Forschung. Es bietet klinisch Forschenden umfassende Unterstützung vonder Studienplanung und -durchführung bis hin zur Studienauswertung.

Link zum [reaction Flyer](https://www.ctu.unibe.ch/unibe/portal/fak_medizin/micro_ctu/content/e182549/e203619/e1449973/e1450036/Reaction_Flyer_A5_20231115_eng.pdf){target="_blank"}.